name: Update repository overview
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          python src/update_repositories.py
      
      - name: Commit changes
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "labot"
          git add .
          git commit -m "Update repository overview"
          git push

